### ISSUE TITLE
How to train my keywords?

### ISSUE THREAD

**Issue by guanjie0618** [NilLlisterri/TinyML-FederatedLearning#1]
When I run fl_server.py, it just run the training datasets.
After the training is complete, there is an error when the button is pressed.
![image](https://user-images.githubusercontent.com/72061770/162117966-c90ee9e8-9dfe-4dc3-9d98-85525273a8be.png)
How to train my keywords with buttons without datasets?
thanks.

**Comment by NilLlisterri** [comment]
Hi  @guanjie0618,

To be able to train without datasets, you have to configure the FL server to not send any samples. This can be done by setting the `experiment` variable to `None`.

The error seems to be due to a desynchronization between the server and the device. I uploaded to master my latest working code, it may fix the issue. Otherwise, I would print on the server every message received from the device to check it is the expected message.

Hope it helps.

**Comment by guanjie0618** [comment]
Hi @NilLlisterri,

Thank you so much for your assistance!
It helps me a lot!
